import type { AddressInfo } from 'node:net';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { schema, type Db } from '@formai/db';

const tenant = { userId: 'u1', orgId: 'org-1', role: 'admin' as const };
const viewerTenant = { userId: 'u2', orgId: 'org-1', role: 'viewer' as const };
let sealSession: (t: typeof tenant | typeof viewerTenant) => string;

let mockDbValue: Db | null = null;
vi.mock('../db.js', () => ({
  get db() {
    return mockDbValue;
  },
  getDbStatus: () => 'unconfigured',
}));

const { createApp } = await import('../app.js');
({ sealSession } = await import('../auth/workos.js'));

function startApp() {
  const app = createApp();
  const server = app.listen(0);
  const { port } = server.address() as AddressInfo;
  return { server, base: `http://127.0.0.1:${port}` };
}

function authHeader(t: typeof tenant | typeof viewerTenant = tenant) {
  return { cookie: `fai_session=${sealSession(t)}` };
}

/** Fill-link create/revoke gate on `forms.edit` (no forms.share/manage exists). */
const EDITOR_PERMS = {
  orgId: 'org-1',
  role: 'admin',
  matrix: { forms: { view: true, create: true, edit: true, delete: true }, submissions: {}, team: {}, billing: {}, audit: {} },
};
const VIEWER_PERMS = {
  orgId: 'org-1',
  role: 'viewer',
  matrix: { forms: { view: true, create: false, edit: false, delete: false }, submissions: {}, team: {}, billing: {}, audit: {} },
};

const BRANDING = {
  logoAssetUrl: null,
  primaryColor: '#253439',
  secondaryColor: '#7c898b',
  accentColor: '#6ec792',
  formFont: 'Inter',
};

const CONTAINER = {
  maxWidth: 600,
  padding: 26,
  radius: 14,
  borderWidth: 1,
  borderColor: '',
  background: '',
  shadow: 'lg',
};

const PUBLISHED_TEMPLATE = {
  id: 't1',
  orgId: 'org-1',
  name: 'Vendor onboarding',
  status: 'published',
  currentVersionId: 'v1',
};

const PUBLISHED_V1 = {
  id: 'v1',
  templateId: 't1',
  state: 'published',
  fields: [{ id: 'abn', type: 'text', label: 'ABN', required: true }],
  container: CONTAINER,
};

const ACTIVE_LINK = {
  id: 'fl1',
  token: 'tok_0123456789abcdef0123456789ab',
  orgId: 'org-1',
  templateId: 't1',
  expiresAt: null,
  active: true,
  createdAt: new Date('2026-07-01T00:00:00Z'),
};

function fakeDb(opts: {
  formTemplatesFindFirst?: unknown;
  formTemplateVersionsFindFirst?: unknown;
  fillLinksFindFirst?: unknown;
  fillLinksFindMany?: unknown[];
  organizationsFindFirst?: unknown;
  rolePermissionsFindFirst?: unknown;
  usersFindFirst?: unknown;
  /** Table whose insert `.values(...)` rejects — simulates a mid-write DB failure. */
  failInsertOf?: unknown;
}) {
  const insertValues = vi.fn();
  const updateSet = vi.fn();
  const rolledBack = vi.fn();

  /** Inserts echo the values passed over DB column defaults, plus a canned
   *  id/createdAt — so tokens generated by the route flow through to the
   *  response assertions, like a real `.returning()` would. */
  function insertResult(table: unknown, v: Record<string, unknown>) {
    const row = { id: 'row-new', active: true, createdAt: new Date('2026-07-02T00:00:00Z'), ...v };
    const awaitable = Promise.resolve(undefined) as Promise<undefined> & {
      returning: () => Promise<unknown[]>;
    };
    awaitable.returning = vi.fn().mockResolvedValue([row]);
    return awaitable;
  }

  /** A `.values(...)` result that rejects, for the `failInsertOf` table. */
  function insertReject(table: unknown, v: Record<string, unknown>) {
    void v;
    const err = new Error('insert_failed');
    const awaitable = Promise.reject(err) as Promise<undefined> & {
      returning: () => Promise<unknown[]>;
    };
    awaitable.catch(() => {}); // keep the base awaitable from surfacing as unhandled
    awaitable.returning = vi.fn().mockRejectedValue(err);
    return awaitable;
  }

  /** Builds an `insert` fn whose `.values()` records via `record` and either
   *  resolves or (for `failInsertOf`) rejects. */
  function makeInsert(record: (table: unknown, v: Record<string, unknown>) => void) {
    return vi.fn((table: unknown) => ({
      values: (v: Record<string, unknown>) => {
        record(table, v);
        return table === opts.failInsertOf ? insertReject(table, v) : insertResult(table, v);
      },
    }));
  }

  const query = {
    formTemplates: { findFirst: vi.fn().mockResolvedValue(opts.formTemplatesFindFirst) },
    formTemplateVersions: { findFirst: vi.fn().mockResolvedValue(opts.formTemplateVersionsFindFirst) },
    fillLinks: {
      findFirst: vi.fn().mockResolvedValue(opts.fillLinksFindFirst),
      findMany: vi.fn().mockResolvedValue(opts.fillLinksFindMany ?? []),
    },
    organizations: { findFirst: vi.fn().mockResolvedValue(opts.organizationsFindFirst) },
    rolePermissions: { findFirst: vi.fn().mockResolvedValue(opts.rolePermissionsFindFirst) },
    users: { findFirst: vi.fn().mockResolvedValue(opts.usersFindFirst) },
  };

  const db = {
    query,
    insert: makeInsert(insertValues),
    update: vi.fn((table: unknown) => ({
      set: (v: unknown) => {
        updateSet(table, v);
        return { where: vi.fn().mockResolvedValue(undefined) };
      },
    })),
    // Runs the callback against a `tx` surface whose inserts are BUFFERED and
    // only replayed into `insertValues` on success — a thrown callback discards
    // the buffer (rollback) and records `rolledBack`, mirroring drizzle.
    transaction: vi.fn(async (fn: (tx: unknown) => Promise<unknown>) => {
      const buffered: [unknown, Record<string, unknown>][] = [];
      const tx = { query, insert: makeInsert((table, v) => buffered.push([table, v])) };
      try {
        const result = await fn(tx);
        for (const [table, v] of buffered) insertValues(table, v);
        return result;
      } catch (err) {
        rolledBack();
        throw err;
      }
    }),
  } as unknown as Db;

  return { db, query, insertValues, updateSet, rolledBack };
}

afterEach(() => {
  vi.clearAllMocks();
  mockDbValue = null;
});

describe('POST /forms/:id/fill-links', () => {
  it('401s with no session cookie', async () => {
    mockDbValue = fakeDb({}).db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/forms/t1/fill-links`, { method: 'POST' });
      expect(res.status).toBe(401);
    } finally {
      server.close();
    }
  });

  it('creates a link with a crypto-random URL-safe token for a published template', async () => {
    const { db, insertValues } = fakeDb({
      rolePermissionsFindFirst: EDITOR_PERMS,
      formTemplatesFindFirst: PUBLISHED_TEMPLATE,
      formTemplateVersionsFindFirst: PUBLISHED_V1,
      usersFindFirst: { id: 'u1', name: 'Ash Wyborn' },
    });
    mockDbValue = db;

    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/forms/t1/fill-links`, {
        method: 'POST',
        headers: { ...authHeader(), 'content-type': 'application/json' },
        body: JSON.stringify({}),
      });
      expect(res.status).toBe(201);
      const body = (await res.json()) as { token: string; url: string };
      expect(typeof body.token).toBe('string');
      expect(body.token.length).toBeGreaterThanOrEqual(32);
      expect(body.token).toMatch(/^[A-Za-z0-9_-]+$/);
      expect(body).toMatchObject({ url: `/fill/${body.token}`, active: true, expiresAt: null });

      const linkInsert = insertValues.mock.calls.find(([table]) => table === schema.fillLinks);
      expect(linkInsert?.[1]).toMatchObject({ orgId: 'org-1', templateId: 't1', token: body.token });

      const auditInsert = insertValues.mock.calls.find(([table]) => table === schema.auditLogEntries);
      expect(auditInsert?.[1]).toMatchObject({ category: 'forms' });
    } finally {
      server.close();
    }
  });

  it('404s for a cross-tenant or missing template', async () => {
    mockDbValue = fakeDb({
      rolePermissionsFindFirst: EDITOR_PERMS,
      formTemplatesFindFirst: undefined,
    }).db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/forms/other-org-form/fill-links`, {
        method: 'POST',
        headers: { ...authHeader(), 'content-type': 'application/json' },
        body: JSON.stringify({}),
      });
      expect(res.status).toBe(404);
    } finally {
      server.close();
    }
  });

  it('409s form_archived when minting on an archived template — existing links keep working, new distribution is blocked', async () => {
    const { db, insertValues } = fakeDb({
      rolePermissionsFindFirst: EDITOR_PERMS,
      formTemplatesFindFirst: { ...PUBLISHED_TEMPLATE, status: 'archived' },
      formTemplateVersionsFindFirst: PUBLISHED_V1,
    });
    mockDbValue = db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/forms/t1/fill-links`, {
        method: 'POST',
        headers: { ...authHeader(), 'content-type': 'application/json' },
        body: JSON.stringify({}),
      });
      expect(res.status).toBe(409);
      expect(await res.json()).toEqual({ error: 'form_archived' });
      expect(insertValues).not.toHaveBeenCalled();
    } finally {
      server.close();
    }
  });

  it('409s when the template has no current version at all', async () => {
    const { db, insertValues } = fakeDb({
      rolePermissionsFindFirst: EDITOR_PERMS,
      formTemplatesFindFirst: { ...PUBLISHED_TEMPLATE, status: 'draft', currentVersionId: null },
    });
    mockDbValue = db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/forms/t1/fill-links`, {
        method: 'POST',
        headers: { ...authHeader(), 'content-type': 'application/json' },
        body: JSON.stringify({}),
      });
      expect(res.status).toBe(409);
      expect(insertValues).not.toHaveBeenCalled();
    } finally {
      server.close();
    }
  });

  it('409s when the current version exists but is an unpublished draft', async () => {
    mockDbValue = fakeDb({
      rolePermissionsFindFirst: EDITOR_PERMS,
      formTemplatesFindFirst: PUBLISHED_TEMPLATE,
      formTemplateVersionsFindFirst: { ...PUBLISHED_V1, state: 'draft' },
    }).db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/forms/t1/fill-links`, {
        method: 'POST',
        headers: { ...authHeader(), 'content-type': 'application/json' },
        body: JSON.stringify({}),
      });
      expect(res.status).toBe(409);
    } finally {
      server.close();
    }
  });

  it('403s (and writes nothing) for a role without forms.edit', async () => {
    const { db, insertValues } = fakeDb({
      rolePermissionsFindFirst: VIEWER_PERMS,
      formTemplatesFindFirst: PUBLISHED_TEMPLATE,
      formTemplateVersionsFindFirst: PUBLISHED_V1,
    });
    mockDbValue = db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/forms/t1/fill-links`, {
        method: 'POST',
        headers: { ...authHeader(viewerTenant), 'content-type': 'application/json' },
        body: JSON.stringify({}),
      });
      expect(res.status).toBe(403);
      expect(insertValues).not.toHaveBeenCalled();
    } finally {
      server.close();
    }
  });
});

describe('GET /forms/:id/fill-links', () => {
  it('lists non-revoked links for the template', async () => {
    mockDbValue = fakeDb({
      rolePermissionsFindFirst: EDITOR_PERMS,
      formTemplatesFindFirst: PUBLISHED_TEMPLATE,
      fillLinksFindMany: [ACTIVE_LINK],
    }).db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/forms/t1/fill-links`, { headers: authHeader() });
      expect(res.status).toBe(200);
      const body = await res.json();
      expect(body).toEqual([
        {
          id: 'fl1',
          token: ACTIVE_LINK.token,
          url: `/fill/${ACTIVE_LINK.token}`,
          expiresAt: null,
          active: true,
          createdAt: '2026-07-01T00:00:00.000Z',
        },
      ]);
    } finally {
      server.close();
    }
  });

  it('404s for a cross-tenant template', async () => {
    mockDbValue = fakeDb({
      rolePermissionsFindFirst: EDITOR_PERMS,
      formTemplatesFindFirst: undefined,
    }).db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/forms/nope/fill-links`, { headers: authHeader() });
      expect(res.status).toBe(404);
    } finally {
      server.close();
    }
  });

  it('403s for a role without forms.edit (tokens are bearer credentials — no enumeration for viewers)', async () => {
    const { db, query } = fakeDb({
      rolePermissionsFindFirst: VIEWER_PERMS,
      formTemplatesFindFirst: PUBLISHED_TEMPLATE,
      fillLinksFindMany: [ACTIVE_LINK],
    });
    mockDbValue = db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/forms/t1/fill-links`, { headers: authHeader(viewerTenant) });
      expect(res.status).toBe(403);
      // Gate fires before any link is read, so no token ever reaches the caller.
      expect(query.fillLinks.findMany).not.toHaveBeenCalled();
    } finally {
      server.close();
    }
  });
});

describe('DELETE /forms/:id/fill-links/:linkId (revoke)', () => {
  it('revokes the link by flipping active to false', async () => {
    const { db, updateSet } = fakeDb({
      rolePermissionsFindFirst: EDITOR_PERMS,
      formTemplatesFindFirst: PUBLISHED_TEMPLATE,
      fillLinksFindFirst: ACTIVE_LINK,
      usersFindFirst: { id: 'u1', name: 'Ash Wyborn' },
    });
    mockDbValue = db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/forms/t1/fill-links/fl1`, {
        method: 'DELETE',
        headers: authHeader(),
      });
      expect(res.status).toBe(200);
      const body = await res.json();
      expect(body).toMatchObject({ id: 'fl1', active: false });

      const linkUpdate = updateSet.mock.calls.find(([table]) => table === schema.fillLinks);
      expect(linkUpdate?.[1]).toEqual({ active: false });
    } finally {
      server.close();
    }
  });

  it('404s for an unknown link id', async () => {
    mockDbValue = fakeDb({
      rolePermissionsFindFirst: EDITOR_PERMS,
      formTemplatesFindFirst: PUBLISHED_TEMPLATE,
      fillLinksFindFirst: undefined,
    }).db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/forms/t1/fill-links/missing`, {
        method: 'DELETE',
        headers: authHeader(),
      });
      expect(res.status).toBe(404);
    } finally {
      server.close();
    }
  });

  it('403s for a role without forms.edit', async () => {
    const { db, updateSet } = fakeDb({
      rolePermissionsFindFirst: VIEWER_PERMS,
      formTemplatesFindFirst: PUBLISHED_TEMPLATE,
      fillLinksFindFirst: ACTIVE_LINK,
    });
    mockDbValue = db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/forms/t1/fill-links/fl1`, {
        method: 'DELETE',
        headers: authHeader(viewerTenant),
      });
      expect(res.status).toBe(403);
      expect(updateSet).not.toHaveBeenCalled();
    } finally {
      server.close();
    }
  });
});

describe('GET /fill/:token (public, no auth)', () => {
  it('serves the current published version fields + branding with no cookie', async () => {
    mockDbValue = fakeDb({
      fillLinksFindFirst: ACTIVE_LINK,
      formTemplatesFindFirst: PUBLISHED_TEMPLATE,
      formTemplateVersionsFindFirst: PUBLISHED_V1,
      organizationsFindFirst: { id: 'org-1', name: 'Charles Hull', plan: 'Business', branding: BRANDING },
    }).db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/fill/${ACTIVE_LINK.token}`);
      expect(res.status).toBe(200);
      const body = (await res.json()) as Record<string, unknown>;
      expect(body).toEqual({
        formName: 'Vendor onboarding',
        orgName: 'Charles Hull',
        orgBranding: BRANDING,
        versionId: 'v1',
        fields: PUBLISHED_V1.fields,
        container: CONTAINER,
      });
      // Never leak org internals beyond name/branding.
      expect(body.plan).toBeUndefined();
      expect(body.orgId).toBeUndefined();
    } finally {
      server.close();
    }
  });

  /**
   * An org that never opened the theme editor must keep the exact payload it
   * had before theming existed — this is the AE3 guarantee on the wire, and
   * this route is the most-hit anonymous endpoint in the product.
   */
  it('omits the theme entirely when neither the org nor the form sets one', async () => {
    mockDbValue = fakeDb({
      fillLinksFindFirst: ACTIVE_LINK,
      formTemplatesFindFirst: PUBLISHED_TEMPLATE,
      formTemplateVersionsFindFirst: PUBLISHED_V1,
      organizationsFindFirst: { id: 'org-1', name: 'Charles Hull', branding: BRANDING },
    }).db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/fill/${ACTIVE_LINK.token}`);
      const body = (await res.json()) as { orgBranding: Record<string, unknown> };
      expect(body.orgBranding.theme).toBeUndefined();
    } finally {
      server.close();
    }
  });

  it('resolves the org theme into the payload when the org sets one', async () => {
    mockDbValue = fakeDb({
      fillLinksFindFirst: ACTIVE_LINK,
      formTemplatesFindFirst: PUBLISHED_TEMPLATE,
      formTemplateVersionsFindFirst: PUBLISHED_V1,
      organizationsFindFirst: {
        id: 'org-1',
        name: 'Charles Hull',
        branding: { ...BRANDING, theme: { radius: 4, density: 'compact' } },
      },
    }).db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/fill/${ACTIVE_LINK.token}`);
      const body = (await res.json()) as {
        orgBranding: { theme: Record<string, unknown> };
      };
      expect(body.orgBranding.theme.radius).toBe(4);
      expect(body.orgBranding.theme.density).toBe('compact');
      // Fully resolved: keys neither layer set still arrive with defaults, so
      // the public page never has to know the precedence rule.
      expect(body.orgBranding.theme.layout).toBe('card');
    } finally {
      server.close();
    }
  });

  /**
   * Covers AE4. The form override wins on the keys it sets and inherits the
   * org's value everywhere else — not the product default.
   */
  it('lets a form override win over the org theme, inheriting the rest', async () => {
    mockDbValue = fakeDb({
      fillLinksFindFirst: ACTIVE_LINK,
      formTemplatesFindFirst: {
        ...PUBLISHED_TEMPLATE,
        themeOverride: { radius: 20 },
      },
      formTemplateVersionsFindFirst: PUBLISHED_V1,
      organizationsFindFirst: {
        id: 'org-1',
        name: 'Charles Hull',
        branding: { ...BRANDING, theme: { radius: 4, density: 'compact' } },
      },
    }).db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/fill/${ACTIVE_LINK.token}`);
      const body = (await res.json()) as {
        orgBranding: { theme: Record<string, unknown> };
      };
      expect(body.orgBranding.theme.radius).toBe(20); // form wins
      expect(body.orgBranding.theme.density).toBe('compact'); // inherited from org
    } finally {
      server.close();
    }
  });

  it('resolves a form override even when the org has no theme', async () => {
    mockDbValue = fakeDb({
      fillLinksFindFirst: ACTIVE_LINK,
      formTemplatesFindFirst: { ...PUBLISHED_TEMPLATE, themeOverride: { layout: 'hero' } },
      formTemplateVersionsFindFirst: PUBLISHED_V1,
      organizationsFindFirst: { id: 'org-1', name: 'Charles Hull', branding: BRANDING },
    }).db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/fill/${ACTIVE_LINK.token}`);
      const body = (await res.json()) as { orgBranding: { theme: Record<string, unknown> } };
      expect(body.orgBranding.theme.layout).toBe('hero');
    } finally {
      server.close();
    }
  });

  it('404s identically for unknown, revoked, and expired tokens', async () => {
    const { db, query } = fakeDb({});
    query.fillLinks.findFirst
      .mockResolvedValueOnce(undefined) // unknown
      .mockResolvedValueOnce({ ...ACTIVE_LINK, active: false }) // revoked
      .mockResolvedValueOnce({ ...ACTIVE_LINK, expiresAt: new Date('2026-01-01T00:00:00Z') }); // expired
    mockDbValue = db;
    const { server, base } = startApp();
    try {
      const unknown = await fetch(`${base}/fill/nope`);
      const revoked = await fetch(`${base}/fill/${ACTIVE_LINK.token}`);
      const expired = await fetch(`${base}/fill/${ACTIVE_LINK.token}`);
      expect(unknown.status).toBe(404);
      expect(revoked.status).toBe(404);
      expect(expired.status).toBe(404);
      const bodies = await Promise.all([unknown.json(), revoked.json(), expired.json()]);
      expect(bodies[1]).toEqual(bodies[0]);
      expect(bodies[2]).toEqual(bodies[0]);
    } finally {
      server.close();
    }
  });

  it('serves the NEW version fields after a newer version is published (fix propagation)', async () => {
    const v2 = {
      id: 'v2',
      templateId: 't1',
      state: 'published',
      fields: [{ id: 'abn', type: 'text', label: 'ABN (11 digits)', required: true }],
      container: CONTAINER,
    };
    mockDbValue = fakeDb({
      fillLinksFindFirst: ACTIVE_LINK,
      formTemplatesFindFirst: { ...PUBLISHED_TEMPLATE, currentVersionId: 'v2' },
      formTemplateVersionsFindFirst: v2,
      organizationsFindFirst: { id: 'org-1', name: 'Charles Hull', branding: BRANDING },
    }).db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/fill/${ACTIVE_LINK.token}`);
      expect(res.status).toBe(200);
      const body = (await res.json()) as { versionId: string; fields: unknown };
      expect(body.versionId).toBe('v2');
      expect(body.fields).toEqual(v2.fields);
    } finally {
      server.close();
    }
  });

  it('keeps serving an ARCHIVED template — archive is metadata-only, the public path reads version state', async () => {
    mockDbValue = fakeDb({
      fillLinksFindFirst: ACTIVE_LINK,
      formTemplatesFindFirst: { ...PUBLISHED_TEMPLATE, status: 'archived' },
      formTemplateVersionsFindFirst: PUBLISHED_V1,
      organizationsFindFirst: { id: 'org-1', name: 'Charles Hull', branding: BRANDING },
    }).db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/fill/${ACTIVE_LINK.token}`);
      expect(res.status).toBe(200);
      const body = (await res.json()) as { versionId: string };
      expect(body.versionId).toBe('v1');
    } finally {
      server.close();
    }
  });
});

describe('POST /fill/:token/submissions (public, no auth)', () => {
  const validBody = {
    versionId: 'v1',
    submitterName: 'Tom Reyes',
    submitterEmail: 'tom@contractor.io',
    values: { abn: '12 345 678 901' },
  };

  it('records a submission pinned to the echoed version, with an audit entry', async () => {
    const { db, insertValues } = fakeDb({
      fillLinksFindFirst: ACTIVE_LINK,
      formTemplatesFindFirst: PUBLISHED_TEMPLATE,
      formTemplateVersionsFindFirst: PUBLISHED_V1,
    });
    mockDbValue = db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/fill/${ACTIVE_LINK.token}/submissions`, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify(validBody),
      });
      expect(res.status).toBe(201);
      const body = await res.json();
      expect(body).toMatchObject({ status: 'submitted' });

      const submissionInsert = insertValues.mock.calls.find(([table]) => table === schema.submissions);
      expect(submissionInsert?.[1]).toMatchObject({
        orgId: 'org-1',
        templateId: 't1',
        templateVersionId: 'v1',
        // Public path: no session, so no server-verified identity — the
        // claimed free-text name/email are kept as unverified input.
        submittedByUserId: null,
        submitterName: 'Tom Reyes',
        submitterEmail: 'tom@contractor.io',
        values: { abn: '12 345 678 901' },
        status: 'submitted',
      });

      const auditInsert = insertValues.mock.calls.find(([table]) => table === schema.auditLogEntries);
      expect(auditInsert?.[1]).toMatchObject({
        orgId: 'org-1',
        actorId: null,
        actorName: 'External fill link',
        category: 'submissions',
      });
    } finally {
      server.close();
    }
  });

  it('accepts a submission for an ARCHIVED template exactly as before archiving', async () => {
    const { db, insertValues } = fakeDb({
      fillLinksFindFirst: ACTIVE_LINK,
      formTemplatesFindFirst: { ...PUBLISHED_TEMPLATE, status: 'archived' },
      formTemplateVersionsFindFirst: PUBLISHED_V1,
    });
    mockDbValue = db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/fill/${ACTIVE_LINK.token}/submissions`, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify(validBody),
      });
      expect(res.status).toBe(201);
      const submissionInsert = insertValues.mock.calls.find(([table]) => table === schema.submissions);
      expect(submissionInsert?.[1]).toMatchObject({ templateId: 't1', templateVersionId: 'v1' });
    } finally {
      server.close();
    }
  });

  it('still accepts an earlier-served versionId after a newer version is published (pins the old one)', async () => {
    // Link's template now points at v2, but the visitor loaded the form when
    // v1 was current — their echo of v1 stays valid because v1 is a real
    // version of the same template.
    const { db, insertValues, query } = fakeDb({
      fillLinksFindFirst: ACTIVE_LINK,
      formTemplatesFindFirst: { ...PUBLISHED_TEMPLATE, currentVersionId: 'v2' },
    });
    query.formTemplateVersions.findFirst.mockResolvedValue(PUBLISHED_V1);
    mockDbValue = db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/fill/${ACTIVE_LINK.token}/submissions`, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify(validBody),
      });
      expect(res.status).toBe(201);
      const submissionInsert = insertValues.mock.calls.find(([table]) => table === schema.submissions);
      expect(submissionInsert?.[1]).toMatchObject({ templateVersionId: 'v1' });
    } finally {
      server.close();
    }
  });

  it('409s (writes nothing) when the versionId is not a version of the link template', async () => {
    const { db, insertValues, query } = fakeDb({
      fillLinksFindFirst: ACTIVE_LINK,
      formTemplatesFindFirst: PUBLISHED_TEMPLATE,
    });
    query.formTemplateVersions.findFirst.mockResolvedValue({ ...PUBLISHED_V1, id: 'v-alien', templateId: 't-other' });
    mockDbValue = db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/fill/${ACTIVE_LINK.token}/submissions`, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ ...validBody, versionId: 'v-alien' }),
      });
      expect(res.status).toBe(409);
      expect(insertValues).not.toHaveBeenCalled();
    } finally {
      server.close();
    }
  });

  it('409s (writes nothing) when the echoed versionId is an unpublished draft of the link template', async () => {
    // The public serve side is published-only — a draft was never served to
    // any visitor, so an echoed draft id can only be fabricated.
    const { db, insertValues, query } = fakeDb({
      fillLinksFindFirst: ACTIVE_LINK,
      formTemplatesFindFirst: PUBLISHED_TEMPLATE,
    });
    query.formTemplateVersions.findFirst.mockResolvedValue({ ...PUBLISHED_V1, id: 'v-draft', state: 'draft' });
    mockDbValue = db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/fill/${ACTIVE_LINK.token}/submissions`, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ ...validBody, versionId: 'v-draft' }),
      });
      expect(res.status).toBe(409);
      expect(await res.json()).toMatchObject({ error: 'version_mismatch' });
      expect(insertValues).not.toHaveBeenCalled();
    } finally {
      server.close();
    }
  });

  it('400s required_fields_missing (writes nothing) when required answers are absent, naming the fields', async () => {
    const { db, insertValues } = fakeDb({
      fillLinksFindFirst: ACTIVE_LINK,
      formTemplatesFindFirst: PUBLISHED_TEMPLATE,
      formTemplateVersionsFindFirst: PUBLISHED_V1, // requires `abn`
    });
    mockDbValue = db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/fill/${ACTIVE_LINK.token}/submissions`, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ ...validBody, values: {} }),
      });
      expect(res.status).toBe(400);
      const body = await res.json();
      expect(body).toEqual({ error: 'required_fields_missing', fields: ['abn'] });
      expect(insertValues).not.toHaveBeenCalled();
    } finally {
      server.close();
    }
  });

  it('enforces required-ness against the PINNED version the visitor echoed, not the current one', async () => {
    // Link template republished to v2, visitor echoes v1: the lookup resolves
    // the echoed v1 and ITS required set drives the failure.
    const { db, query } = fakeDb({
      fillLinksFindFirst: ACTIVE_LINK,
      formTemplatesFindFirst: { ...PUBLISHED_TEMPLATE, currentVersionId: 'v2' },
    });
    query.formTemplateVersions.findFirst.mockResolvedValue({
      ...PUBLISHED_V1,
      fields: [{ id: 'old-field', type: 'text', label: 'Old required', required: true, source: 'built' }],
    });
    mockDbValue = db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/fill/${ACTIVE_LINK.token}/submissions`, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ ...validBody, values: {} }),
      });
      expect(res.status).toBe(400);
      const body = await res.json();
      expect(body).toEqual({ error: 'required_fields_missing', fields: ['old-field'] });
    } finally {
      server.close();
    }
  });

  it('400s (writes nothing) on malformed values — nested objects are not SubmissionValues', async () => {
    const { db, insertValues } = fakeDb({
      fillLinksFindFirst: ACTIVE_LINK,
      formTemplatesFindFirst: PUBLISHED_TEMPLATE,
      formTemplateVersionsFindFirst: PUBLISHED_V1,
    });
    mockDbValue = db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/fill/${ACTIVE_LINK.token}/submissions`, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ ...validBody, values: { abn: { nested: 'object' } } }),
      });
      expect(res.status).toBe(400);
      expect(insertValues).not.toHaveBeenCalled();
    } finally {
      server.close();
    }
  });

  it('accepts the full SubmissionValue union: strings, numbers, booleans, string[], repeating rows, null', async () => {
    const { db } = fakeDb({
      fillLinksFindFirst: ACTIVE_LINK,
      formTemplatesFindFirst: PUBLISHED_TEMPLATE,
      formTemplateVersionsFindFirst: PUBLISHED_V1,
    });
    mockDbValue = db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/fill/${ACTIVE_LINK.token}/submissions`, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({
          ...validBody,
          values: {
            // `abn` stays present — PUBLISHED_V1 requires it and this test is
            // about the accepted value SHAPES, not required enforcement.
            abn: '12 345 678 901',
            name: 'Tom',
            count: 3,
            confirmed: true,
            tags: ['a', 'b'],
            rows: [{ item: 'Ladder', qty: 2, ok: true, note: null }],
            skipped: null,
          },
        }),
      });
      expect(res.status).toBe(201);
    } finally {
      server.close();
    }
  });

  it('404s for a revoked token (both verbs are indistinguishable from unknown)', async () => {
    const { db, insertValues } = fakeDb({
      fillLinksFindFirst: { ...ACTIVE_LINK, active: false },
    });
    mockDbValue = db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/fill/${ACTIVE_LINK.token}/submissions`, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify(validBody),
      });
      expect(res.status).toBe(404);
      expect(await res.json()).toEqual({ error: 'not_found' });
      expect(insertValues).not.toHaveBeenCalled();
    } finally {
      server.close();
    }
  });

  it('rolls back the submission (500, nothing persisted) when the audit insert fails', async () => {
    const { db, insertValues, rolledBack } = fakeDb({
      fillLinksFindFirst: ACTIVE_LINK,
      formTemplatesFindFirst: PUBLISHED_TEMPLATE,
      formTemplateVersionsFindFirst: PUBLISHED_V1,
      failInsertOf: schema.auditLogEntries,
    });
    mockDbValue = db;
    const { server, base } = startApp();
    try {
      const res = await fetch(`${base}/fill/${ACTIVE_LINK.token}/submissions`, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify(validBody),
      });
      expect(res.status).toBe(500);
      // The audit failure aborted the transaction, so the submission never
      // committed — no submissions insert survived the rollback.
      expect(rolledBack).toHaveBeenCalledTimes(1);
      const submissionInsert = insertValues.mock.calls.find(([table]) => table === schema.submissions);
      expect(submissionInsert).toBeUndefined();
    } finally {
      server.close();
    }
  });
});
