// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-forms/Minimal.tsx": () => import("../components/mockups/login-forms/Minimal.tsx"),
  "./components/mockups/login-forms/Split.tsx": () => import("../components/mockups/login-forms/Split.tsx"),
  "./components/mockups/login-forms/SplitA.tsx": () => import("../components/mockups/login-forms/SplitA.tsx"),
  "./components/mockups/login-forms/SplitB.tsx": () => import("../components/mockups/login-forms/SplitB.tsx")
};
